using System;
using System.IO;
using System.Linq;
using Common_Library;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using System.Reflection;
using System.Diagnostics;
using System.Windows.Forms;
using QuestPDF.Infrastructure;
using System.Collections.Generic;
using University_Housing_Management_Project.Global;

namespace University_Housing_Management_Project.Helpers.Pdf
{
    public static class PdfGenerator
    {
        static PdfGenerator()
        {
            QuestPDF.Settings.License = LicenseType.Community;
        }
        private static byte[] ImageToBytes(System.Drawing.Image image)
        {
            using (var ms = new MemoryStream())
            {
                image.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                return ms.ToArray();
            }
        }
        public static void Export<T>(List<T> data, string title)
        {

            if (data == null || data.Count == 0)
            {
                ShowMessagebox.Information("No data to export.", "Information");
                return;
            }


            SaveFileDialog save = new SaveFileDialog();

            save.Filter = "PDF Files (*.pdf)|*.pdf";
            save.FileName = title;
            save.DefaultExt = "pdf";

            if (save.ShowDialog() != DialogResult.OK)
                return;


            var properties = typeof(T)
                    .GetProperties()
                    .Where(p => !Attribute.IsDefined(p, typeof(PdfIgnoreAttribute)))
                    .ToArray();

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);

                    page.Margin(20);

                    page.DefaultTextStyle(TextStyle.Default.FontSize(11));

                    page.Header()
                        .Column(column =>
                        {
                            column.Item()
                                .Row(row =>
                                {
                                    row.ConstantItem(70)
                                        .Image(ImageToBytes(Properties.Resources._1757680871045));

                                    row.RelativeItem()
                                        .AlignCenter()
                                        .AlignMiddle()
                                        .Text("University Housing Management")
                                        .Bold()
                                        .FontSize(22);
                                });

                            column.Item().PaddingTop(10);

                            column.Item()
                                .Text($"Generated By : {CurrentUser.Username}")
                                    .FontColor(Colors.Grey.Darken2);

                            column.Item()
                                .Text($"Generated At : {DateTime.Now:dd/MM/yyyy HH:mm}")
                                .FontColor(Colors.Grey.Darken2);

                            column.Item().PaddingTop(15);

                            column.Item()
                                .AlignCenter()
                                .Text(title)
                                .Bold()
                                .FontSize(16);
                        });

                    page.Content().Column(column =>
                    {

                        column.Item().LineHorizontal(1);
                        column.Item().PaddingVertical(10);
                        column.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                foreach (var property in properties)
                                    columns.RelativeColumn();
                            });

                            table.Header(header =>
                            {
                                foreach (var property in properties)
                                {
                                    
                                    var displayNameAttribute = property.
                                        GetCustomAttribute<PdfDisplayNameAttribute>();

                                    string headerText =
                                        displayNameAttribute?.DisplayName ?? property.Name;

                                    header.Cell()
                                        .Background("#1E3C5A")
                                        .Border(1)
                                        .Padding(5)
                                        .AlignCenter()
                                        .Text(headerText)
                                        .FontColor(Colors.White)
                                        .Bold();
                                }
                            });

                            foreach (var item in data)
                            {
                                foreach (var property in properties)
                                {
                                    object value = property.GetValue(item);

                                    table.Cell()
                                        .Border(1)
                                        .Padding(5)
                                        .AlignCenter()
                                        .Text(value?.ToString() ?? "");
                                }
                            }
                        });

                    });
                        

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Page ");
                            text.CurrentPageNumber();
                            text.Span(" of ");
                            text.TotalPages();
                        });
                });
            })
            .GeneratePdf(save.FileName);

            Process.Start(new ProcessStartInfo
            {
                FileName = save.FileName,
                UseShellExecute = true
            });
        }

    }
}
